### ISSUE TITLE
About X_cond_Y_marginals

### ISSUE THREAD

**Issue by SeongJinAhn** [Graph-COM/GraphMaker#2]
How can I use X_cond_Y_marginals?

Is it available in this implementation?

**Comment by mufeili** [comment]
Thank you for your interest in our work!

Currently, `X_cond_Y_marginals` is not used in this codebase. This was originally computed to extend baseline models like Erdős–Rényi (ER) and Graph Auto-Encoder (GAE) for our paper, allowing generating synthetic node features in addition to the graph structures. If you find this confusing, I can remove the corresponding lines of code.

**Comment by mufeili** [comment]
Close this issue for now due to inactivity. Feel free to reopen it if you have further questions.
